In [97]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import classification_report
from imblearn.combine import SMOTEENN

In [98]:
df=pd.read_csv(r"C:\Users\SOUMYA\New folder (3)\myenv\machine learning project\Customer-Churn.csv")

In [99]:
#df.drop("Unnamed: 0",axis=1,inplace=True)

In [101]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [103]:
df["TotalCharges"]=df["TotalCharges"].replace(' ',np.nan)

In [104]:
df["TotalCharges"].isnull().sum()

11

In [105]:
df.dropna(how='any',inplace=True)

In [106]:
df["TotalCharges"].isnull().sum()

0

In [107]:
df["TotalCharges"]=df["TotalCharges"].astype("float")

In [108]:
df.drop("customerID",axis=1,inplace=True)

In [109]:
df.head(2)

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   

  PaperlessBilling     PaymentMethod  MonthlyCharges  TotalCharges Churn  
0              Yes  Electronic check           29.85         29.85    No  
1               No      Mailed check           56.95       1889.50    No

In [110]:
le={}
for column in df.columns:
    if df[column].dtypes == 'object':
        le[column]=LabelEncoder()
        df[column]=le[column].fit_transform(df[column])

In [111]:
df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0              1                0               0             2   
1              0                0               2             0   
2              0                0               2             2   
3              1                0               2             0   
4              0                1               0             0   

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                 0            0            0                0         0   
1                 2            0            0                0         1   
2                 0            0            0                0         0   
3                 2            2            0                0         1   
4                 0            0            0                0         0   

   PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                 1              2           29.85         29.85      0  
1                 0              3           56.95       1889.50      0  
2                 1              3           53.85        108.15      1  
3                 0              0           42.30       1840.75      0  
4                 1              2           70.70        151.65      1

In [112]:
x=df.drop("Churn",axis=1)
y=df["Churn"]

In [113]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=41)

In [114]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5625, 19), (1407, 19), (5625,), (1407,))

In [115]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [116]:
####LogisticRegression model

In [117]:
lr_model=LogisticRegression()

In [118]:
lr_model.fit(x_train,y_train)
y_pred=lr_model.predict(x_test)
y_pred

array([1, 0, 0, ..., 0, 1, 1])

In [119]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[910, 113],
       [182, 202]], dtype=int64)

In [120]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1023
           1       0.64      0.53      0.58       384

    accuracy                           0.79      1407
   macro avg       0.74      0.71      0.72      1407
weighted avg       0.78      0.79      0.78      1407



In [121]:
sm=SMOTEENN()
x_resampled, y_resampled = sm.fit_resample(x,y)
xr_train,xr_test,yr_train,yr_test=train_test_split(x_resampled, y_resampled,test_size=0.2)

In [122]:
lr_rs_model=LogisticRegression()
lr_rs_model.fit(xr_train,yr_train)
yr_pred=lr_rs_model.predict(xr_test)
yr_pred

C:\Users\SOUMYA\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([1, 0, 1, ..., 1, 0, 0])

In [123]:
print(classification_report(yr_test,yr_pred))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92       515
           1       0.93      0.94      0.94       659

    accuracy                           0.93      1174
   macro avg       0.93      0.93      0.93      1174
weighted avg       0.93      0.93      0.93      1174



In [124]:
cm=confusion_matrix(yr_test,yr_pred)
cm

array([[471,  44],
       [ 38, 621]], dtype=int64)

In [125]:
lr_rs_model.score(xr_test,yr_test)

0.9301533219761499

In [126]:
### RandomForest model

In [127]:
rf_model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [128]:
rf_model.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [129]:
y_pred2=rf_model.predict(x_test)
y_pred2

array([1, 0, 0, ..., 0, 1, 1])

In [130]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.81      0.91      0.86      1023
           1       0.64      0.42      0.51       384

    accuracy                           0.78      1407
   macro avg       0.72      0.67      0.68      1407
weighted avg       0.76      0.78      0.76      1407



In [131]:
rf_rs_model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)
rf_rs_model.fit(xr_train,yr_train)
rf_pred=rf_rs_model.predict(xr_test)
rf_pred

array([1, 0, 1, ..., 1, 0, 0])

In [132]:
rf_rs_model.score(xr_test,yr_test)

0.9335604770017035

In [133]:
print(classification_report(yr_test,rf_pred))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92       515
           1       0.93      0.96      0.94       659

    accuracy                           0.93      1174
   macro avg       0.93      0.93      0.93      1174
weighted avg       0.93      0.93      0.93      1174



In [134]:
###DecisionTree model

In [135]:
dt_model=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)
dt_model.fit(x_train,y_train)
y_pred3=dt_model.predict(x_test)
y_pred3

array([1, 0, 0, ..., 0, 1, 1])

In [136]:
print(classification_report(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84      1023
           1       0.59      0.45      0.51       384

    accuracy                           0.76      1407
   macro avg       0.70      0.67      0.68      1407
weighted avg       0.75      0.76      0.75      1407



In [137]:
dt_rs_model=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)
dt_rs_model.fit(xr_train,yr_train)
dt_pred=dt_rs_model.predict(xr_test)
dt_pred

array([1, 0, 1, ..., 1, 0, 0])

In [138]:
print(classification_report(yr_test,dt_pred))

              precision    recall  f1-score   support

           0       0.92      0.90      0.91       515
           1       0.92      0.94      0.93       659

    accuracy                           0.92      1174
   macro avg       0.92      0.92      0.92      1174
weighted avg       0.92      0.92      0.92      1174



In [139]:
print(confusion_matrix(yr_test, dt_pred))

[[462  53]
 [ 40 619]]


In [155]:
import pickle

In [156]:
filename='model.sav'

In [157]:
pickle.dump(rf_rs_model, open(filename, 'wb'))

In [158]:
load_model = pickle.load(open(filename, 'rb'))

In [159]:
model_score= load_model.score(xr_test, yr_test)

In [160]:
model_score

0.9335604770017035

In [161]:
rf_rs_model.predict([[1,0,0,0,34,0,0,2,0,2,0,0,0,1,0,0,3,56.95,1889.50]])[0]

C:\Users\SOUMYA\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


0